"""Write a minimal Docker-ready prediction service bundle next to a model artifact."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

DOCKERFILE = """\
FROM python:3.12-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1 \\
    PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY model.joblib metadata.json ./
COPY app ./app

EXPOSE 8080
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]
"""

REQUIREMENTS = """\
fastapi>=0.115.0
uvicorn[standard]>=0.32.0
scikit-learn>=1.5.0
pandas>=2.2.0
joblib>=1.4.0
numpy>=2.0.0
"""

STANDALONE_APP = '''\
"""Standalone prediction API exported by Atlas Deployment.

Build:  docker build -t atlas-model .
Run:    docker run -p 8080:8080 atlas-model
Predict: POST /predict  {"instances": [{"age": 40, "income": 70000}]}
"""

from __future__ import annotations

import json
from pathlib import Path

import joblib
import pandas as pd
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field

ROOT = Path(__file__).resolve().parent.parent
PIPELINE = joblib.load(ROOT / "model.joblib")
METADATA = json.loads((ROOT / "metadata.json").read_text(encoding="utf-8"))

app = FastAPI(title="Atlas Deployed Model", version="0.1.0")


class PredictRequest(BaseModel):
    instances: list[dict] = Field(min_length=1)


@app.get("/health")
def health() -> dict:
    return {"status": "healthy", "model_key": METADATA.get("model_key")}


@app.get("/metadata")
def metadata() -> dict:
    return METADATA


@app.post("/predict")
def predict(payload: PredictRequest) -> dict:
    frame = pd.DataFrame(payload.instances)
    missing = [c for c in METADATA["feature_columns"] if c not in frame.columns]
    if missing:
        raise HTTPException(status_code=400, detail=f"Missing features: {missing}")
    frame = frame[METADATA["feature_columns"]]
    preds = PIPELINE.predict(frame)
    result: dict = {"predictions": preds.tolist()}
    if hasattr(PIPELINE, "predict_proba"):
        try:
            result["probabilities"] = PIPELINE.predict_proba(frame).tolist()
        except Exception:
            pass
    return result
'''

README = """\
# Atlas exported model bundle

This folder was generated by Atlas Deployment.

## Run with Docker

```bash
docker build -t atlas-model .
docker run --rm -p 8080:8080 atlas-model
curl http://localhost:8080/health
```

## Predict

```bash
curl -X POST http://localhost:8080/predict \\
  -H "Content-Type: application/json" \\
  -d '{"instances":[{"age":40,"income":70000}]}'
```
"""


def write_deployment_bundle(
    bundle_dir: Path,
    *,
    model_path: Path,
    metadata: dict[str, Any],
) -> Path:
    """Create Dockerfile + standalone FastAPI app beside the serialized model."""
    bundle_dir.mkdir(parents=True, exist_ok=True)
    app_dir = bundle_dir / "app"
    app_dir.mkdir(parents=True, exist_ok=True)

    target_model = bundle_dir / "model.joblib"
    target_model.write_bytes(model_path.read_bytes())

    (bundle_dir / "metadata.json").write_text(
        json.dumps(metadata, indent=2),
        encoding="utf-8",
    )
    (bundle_dir / "Dockerfile").write_text(DOCKERFILE, encoding="utf-8")
    (bundle_dir / "requirements.txt").write_text(REQUIREMENTS, encoding="utf-8")
    (bundle_dir / "README.md").write_text(README, encoding="utf-8")
    (app_dir / "__init__.py").write_text("", encoding="utf-8")
    (app_dir / "main.py").write_text(STANDALONE_APP, encoding="utf-8")

    return bundle_dir
